

http://localhost:8000/api/user
Accept: application/json
Authorization: Bearer 1|HGLE2nY4XewhpBBFtjeho9FQAo7Nzjcse2c6rFG0

### send-email

POST http://localhost:8000/api/send-email
Accept: application/json
Content-Type: application/json

{
    "mailTo": "admin@nikolav.rs"
}

###

POST https://qyhnjtvrhog.herokuapp.com/api/authenticate
Accept: application/json
Content-Type: application/json

{
    "email": "user.1@email.com",
    "password": "122333"
}

###

https://qyhnjtvrhog.herokuapp.com/api/messages
Accept: application/json

###

POST https://qyhnjtvrhog.herokuapp.com/api/messages
Accept: application/json
Content-Type: application/json

{
  "title": "@m-2",
  "content": "messages-2",
  "auth": "user.1"
}

###
