

http://localhost:8000/api/user
Accept: application/json
Authorization: Bearer 3|XdnJ8XAQ7vTANp2PEckQULfbdeS7kaBrRTVqcHog

### send-email

POST http://localhost:8000/api/send-email
Accept: application/json
Content-Type: application/json

{
    "mailTo": "admin@nikolav.rs"
}

###

POST http://localhost:8000/api/authenticate
Accept: application/json
Content-Type: application/json

{
    "email": "user.1@email.com",
    "password": "122333"
}

###

https://qyhnjtvrhog.herokuapp.com/api/messages
Accept: application/json

###

POST https://qyhnjtvrhog.herokuapp.com/api/messages
Accept: application/json
Content-Type: application/json

{
  "title": "@m-2",
  "content": "messages-2",
  "auth": "user.1"
}

###

POST http://127.0.0.1:8000/api/ijlwydmfdeo
Accept: application/json
Content-Type: application/json

{
    "calculation": "{\"fq\": \"daily\"}"
}


###

