

http://localhost:8000/api/user
Accept: application/json
Authorization: Bearer 94|S8zX1EvKioyurUTr47HNFgIDGbD6Q4z4q8Ra7wbJ

### send-email

POST http://localhost:8000/api/send-email
Accept: application/json

###

POST http://localhost:8000/api/authenticate
Accept: application/json
Content-Type: application/json

{
    "email": "user.3@email.com",
    "password": "122333"
}

###

http://localhost:8000/api/appdata
Accept: application/json

###

POST http://localhost:8000/api/register
Accept: application/json
Content-Type: application/json

{
    "name": "user.3",
    "email": "user.3@email.com",
    "password": "122333",
    "password_confirmation": "122333"
}

###

PATCH http://localhost:8000/api/appdata/4
Accept: application/json
Content-Type: application/json
Authorization: Bearer 62|W12iu3CTCuKNs6m1uHWQR390ujb3evHMMngOIl6Z

{
    "value": "true"
}

###

DELETE http://localhost:8000/api/appdata/1
Accept: application/json

###

POST http://localhost:8000/api/logout
Accept: application/json
Authorization: Bearer 78|fklG1wowH12MnYZE2DZiSli74G6OeiG427AsAu6L

###

